[WIP] Deprecated retired options
CLIUtils/CLI11 pull request #358
Opened 2019-12-01 14:36 UTC by phlptp

adds helper functions for retired and deprecated options

Fixes #275

2019-12-01 14:38 UTC, phlptp commented
TODO
- [ ] add documentation
- [ ] add some comments and explanation to the example
- [ ] verify code coverage

2019-12-03 19:16 UTC, cbachhuber requested changes
Thank you for this addition! Looks very good already, I only have minor remarks.

2019-12-03 19:16 UTC, cbachhuber commented on examples/retired.cpp
> +// This example show the usage of the retired and deprecated option helper methods
```suggestion
// This example shows the usage of the retired and deprecated option helper methods
```

2019-12-03 19:16 UTC, cbachhuber commented on examples/retired.cpp
> +    // specify that a no existing option is retired
```suggestion
    // specify that a non-existing option is retired
```

2019-12-03 19:16 UTC, cbachhuber commented on examples/retired.cpp
> +    // specify that an existing option is retired and non-functional this will replace the option with another that
```suggestion
    // specify that an existing option is retired and non-functional: this will replace the option with another that
```

2019-12-03 19:16 UTC, cbachhuber commented on examples/retired.cpp
> +    // deprecate an existing option and specify a recommended replacement
```suggestion
    // deprecate an existing option and specify the recommended replacement
```

2019-12-03 19:16 UTC, cbachhuber commented on examples/retired.cpp
> +    CLI11_PARSE(app, argc, argv);
Many other examples do a std::cout at the end, to show what is going on. Does that make sense here as well?

2019-12-03 19:16 UTC, cbachhuber commented on include/CLI/App.hpp
> +    Validator cv{[opt2](std::string &) {
Why is this object called cv? Could you find a more epressive name?

2019-12-03 19:16 UTC, cbachhuber commented on include/CLI/App.hpp
> +/// Helper function to mark an option as deprecated
```suggestion
/// Helper function to mark an option as retired
```

2019-12-03 19:16 UTC, cbachhuber commented on include/CLI/App.hpp
> +/// Helper function to mark an option as deprecated
```suggestion
/// Helper function to mark an option as retired
```

2019-12-03 19:16 UTC, cbachhuber commented on include/CLI/App.hpp
> +inline void deprecate_option(App &app, const std::string &option_name, const std::string &replacement = "") {
My IDE complains that this function is never used. Is my IDE wrong? Manually, I also can't find usages and wonder how you get 100% coverage.

2019-12-03 19:16 UTC, cbachhuber commented on include/CLI/App.hpp
> +    auto ropt = temp.add_option(opt->get_name(false, true))
Why do you need ropt in addition to opt? Consider a more descriptive name for this object

2019-12-03 19:53 UTC, phlptp commented on examples/retired.cpp
> +    CLI11_PARSE(app, argc, argv);
Maybe something that prints out if the '--not_deprecated` or no options were passed, just so there is always guaranteed to be some output?

2019-12-03 19:54 UTC, phlptp commented on include/CLI/App.hpp
> +inline void deprecate_option(App &app, const std::string &option_name, const std::string &replacement = "") {
I thought I was using it one of the tests but I will double check that and make sure

2019-12-03 19:55 UTC, phlptp commented on include/CLI/App.hpp
> +    auto ropt = temp.add_option(opt->get_name(false, true))
We need to create a temporary psuedo copy of the option before destroying the original, and then copying the copy with the critical info.    I will rename it something more descriptive though.

2019-12-03 19:56 UTC, phlptp commented on include/CLI/App.hpp
> +    Validator cv{[opt2](std::string &) {
`custom validator`,  I will rename it

2019-12-03 20:19 UTC, cbachhuber commented on examples/retired.cpp
> +    CLI11_PARSE(app, argc, argv);
Good suggestion, I like it!

2019-12-03 20:19 UTC, cbachhuber commented on include/CLI/App.hpp
> +inline void deprecate_option(App &app, const std::string &option_name, const std::string &replacement = "") {
Thanks!

2019-12-04 19:50 UTC, cbachhuber approved these changes
Looks good, thanks! :+1:

2019-12-04 19:52 UTC, henryiii approved these changes

2019-12-04 19:52 UTC, henryiii commented
Looks good to me, are you ready to merge?

2019-12-04 19:59 UTC, phlptp commented
I think it is ready.

2019-12-05 02:16 UTC, merged